development:
  adapter: postgresql
  encoding: unicode
  database: flickr_sandbox_development
  pool: 5
  username: baracus

  adapter: postgresql
  encoding: unicode
  database: flickr_sandbox_test
  pool: 5
  username: baracus

production:
  adapter: postgresql
  encoding: unicode
  database: flickr_sandbox_production
  pool: 5
  username: baracus

